### ISSUE TITLE
Android workflow is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7469]
For example: https://app.circleci.com/pipelines/github/pytorch/vision/24123/workflows/5ab26cc9-2561-47f7-8a16-bb5ed7cdd021/jobs/1856621

```
2023-03-27T12:03:27.297+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] In file included from /home/circleci/project/torchvision/csrc/ops/roi_align.cpp:1:
2023-03-27T12:03:27.297+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] /home/circleci/project/torchvision/csrc/ops/roi_align.h:22:10: error: no type named 'SymInt' in namespace 'c10'
2023-03-27T12:03:27.297+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     c10::SymInt pooled_height,
2023-03-27T12:03:27.297+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     ~~~~~
```

Most likely caused by #7448.

cc @seemethere @ezyang

**Comment by ezyang** [comment]
We define SymInt in mobile builds but it is trivial around int, so this is pribably an IWYU problem
