### PR TITLE
Fix build with ffmpeg 6.0

### LINKED ISSUE #7998: torchvision 0.15.2 + ffmpeg 6.0 build error: ‘AV_CODEC_CAP_INTRA_ONLY’ was not declared
### 🐛 Describe the bug

The build error is if it's compiled with ffmpeg 6:
...
vision-0.15.2/torchvision/csrc/io/decoder/stream.cpp:68:42: error: ‘AV_CODEC_CAP_INTRA_ONLY’ was not declared in this scope; did you mean ‘AV_CODEC_PROP_INTRA_ONLY’
...
The source of the problem is renamed macro AV_CODEC_CAP_INTRA_ONLY. The following trivial patch resolve the issue:
--- a/torchvision/csrc/io/decoder/stream.cpp    2023-09-28 11:34:50.636149910 +1000
+++ b/torchvision/csrc/io/decoder/stream.cpp    2023-09-28 11:32:02.002280926 +1000
@@ -65,7 +65,7 @@
     // otherwise set sensible defaults
     // with the special case for the different MPEG4 codecs
     // that don't have threading context functions
-    if (codecCtx_->codec->capabilities & AV_CODEC_CAP_INTRA_ONLY) {
+    if (codecCtx_->codec->capabilities & AV_CODEC_PROP_INTRA_ONLY) {
       codecCtx_->thread_type = FF_THREAD_FRAME;
       codecCtx_->thread_count = 2;
     } else {

### Versions

Used python 3.10, pytorch-2.0.1, caffe2-2.0.1
I don't use pip on the host, so:
python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "/home/avz/collect_env.py", line 611, in <module>
    main()
  File "/home/avz/collect_env.py", line 594, in main
    output = get_pretty_env_info()
  File "/home/avz/collect_env.py", line 589, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/avz/collect_env.py", line 427, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/home/avz/collect_env.py", line 399, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
  File "/home/avz/collect_env.py", line 384, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

### PR DESCRIPTION
**Pull request by zboszor**
ffmpeg has this more than 3 years old changelog entry:
```
2020-05-21 - 13b1bbff0b - lavc 58.86.101 - avcodec.h
  Deprecated AV_CODEC_CAP_INTRA_ONLY and AV_CODEC_CAP_LOSSLESS.
```

Fixes #7998

### CODE REVIEW

**Comment by surak** [comment]
Still not there for 0.16.2

**Comment by xvdp** [comment]
I don't know if this is related or not. But I have had much trouble using later versions of ffmpeg with torchvision. 

On cuda 11.8 Ubuntu 22,04 torch 2.0.1 I could not get the the ffmpeg version I was using (5.1.2) . conda install torchvision would clobber it - either making torchvision of ffmpeg or both unusable depending in the installation order.

I resorted to create a docker image where I would  first set channels strict, install torch , then set channels to flexible and install ffmpeg==5.1.2, then pull  and compile torchvision.  I encountered to errrors on doing that (clearly there could be some as ai didnt run a test suite, simply used it for my video projects)

Thinking that this may have been fixed, I just built a new image with cuda 12.1 and torch 2.1.2 and tried installing torchvision 16.2 with the rest of the conda packages. Unfortunately the ffmpeg installation got mangled up so I will resort to compiling vision again from github.

Error: when I type`$ ffmpeg` i get `ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory`

ffmpeg is evolving so fast that it would be great that torchvision does not clobbler it. 

Thanks!

**Comment by surak** [comment]
@xvdp we use the patch in production. It works for us.

**Review by NicolasHug — APPROVED** [review]
Thanks for the fix and for your patience @zboszor . Let me merge this now, it should be available with torchvision 0.18.

------

Notes for myself: video tests and CI building is completely toasted https://github.com/pytorch/vision/issues/8162. I verified locally that this PR works on ffmpeg6. This doesn't introduce any new construct so it should still work fine with previous versions of ffmpeg.

<details>

```
(ffmpeg6) ➜  vision git:(fix-with-ffmpeg6) ✗ ldd build/lib.linux-x86_64-cpython-310/torchvision/video_reader.so
	linux-vdso.so.1 (0x00007ffd78f94000)
	libavcodec.so.60 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavcodec.so.60 (0x00007fb5dfe00000)
	libavformat.so.60 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavformat.so.60 (0x00007fb5dfa00000)
	libavutil.so.58 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavutil.so.58 (0x00007fb5de800000)
	libswresample.so.4 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libswresample.so.4 (0x00007fb5e122f000)
	libswscale.so.7 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libswscale.so.7 (0x00007fb5e1198000)
	libc10.so => not found
	libtorch.so => not found
	libtorch_cpu.so => not found
	libtorch_python.so => not found
	libstdc++.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libstdc++.so.6 (0x00007fb5de61d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb5dfd22000)
	libgcc_s.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libgcc_s.so.1 (0x00007fb5e1160000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb5de400000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb5e12cb000)
	libvpx.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libvpx.so.8 (0x00007fb5de209000)
	libiconv.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libiconv.so.2 (0x00007fb5df919000)
	liblzma.so.5 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./liblzma.so.5 (0x00007fb5e1130000)
	libdav1d.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libdav1d.so.6 (0x00007fb5de011000)
	libaom.so.3 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libaom.so.3 (0x00007fb5dd800000)
	libmp3lame.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libmp3lame.so.0 (0x00007fb5dfcaa000)
	libopus.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libopus.so.0 (0x00007fb5ddfb0000)
	libSvtAv1Enc.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libSvtAv1Enc.so.1 (0x00007fb5dd000000)
	libx264.so.164 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libx264.so.164 (0x00007fb5dcc00000)
	libx265.so.199 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libx265.so.199 (0x00007fb5db800000)
	libopenh264.so.7 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libopenh264.so.7 (0x00007fb5dcedf000)
	libz.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libz.so.1 (0x00007fb5e1111000)
	libva.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva.so.2 (0x00007fb5ddf7f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb5e110c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb5e1107000)
	libxml2.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libxml2.so.2 (0x00007fb5dca97000)
	libbz2.so.1.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libbz2.so.1.0 (0x00007fb5dfc96000)
	libgnutls.so.30 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libgnutls.so.30 (0x00007fb5db400000)
	libva-drm.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva-drm.so.2 (0x00007fb5e1100000)
	libva-x11.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva-x11.so.2 (0x00007fb5e10f9000)
	libX11.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libX11.so.6 (0x00007fb5db6bb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fb5df914000)
	libicui18n.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicui18n.so.73 (0x00007fb5db000000)
	libicuuc.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicuuc.so.73 (0x00007fb5dac00000)
	libicudata.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicudata.so.73 (0x00007fb5d8c00000)
	libp11-kit.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libp11-kit.so.0 (0x00007fb5daed2000)
	libidn2.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libidn2.so.0 (0x00007fb5ddf2c000)
	libtasn1.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libtasn1.so.6 (0x00007fb5df8ff000)
	libnettle.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libnettle.so.8 (0x00007fb5dd7aa000)
	libhogweed.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libhogweed.so.6 (0x00007fb5db663000)
	libgmp.so.10 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libgmp.so.10 (0x00007fb5db358000)
	libdrm.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libdrm.so.2 (0x00007fb5de606000)
	libXext.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libXext.so.6 (0x00007fb5ddf17000)
	libXfixes.so.3 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libXfixes.so.3 (0x00007fb5ddf0e000)
	libX11-xcb.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libX11-xcb.so.1 (0x00007fb5ddf09000)
	libxcb.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libxcb.so.1 (0x00007fb5dd77e000)
	libxcb-dri3.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libxcb-dri3.so.0 (0x00007fb5ddf03000)
	libffi.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libffi.so.8 (0x00007fb5dcece000)
	libunistring.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libunistring.so.2 (0x00007fb5d8a7b000)
	libXau.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libXau.so.6 (0x00007fb5dcec9000)
	libXdmcp.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libXdmcp.so.6 (0x00007fb5dca8f000)

```

```py
(ffmpeg6) ➜  vision git:(fix-with-ffmpeg6) ✗ ldd build/lib.linux-x86_64-cpython-310/torchvision/video_reader.so
	linux-vdso.so.1 (0x00007ffd78f94000)
	libavcodec.so.60 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavcodec.so.60 (0x00007fb5dfe00000)
	libavformat.so.60 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavformat.so.60 (0x00007fb5dfa00000)
	libavutil.so.58 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libavutil.so.58 (0x00007fb5de800000)
	libswresample.so.4 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libswresample.so.4 (0x00007fb5e122f000)
	libswscale.so.7 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libswscale.so.7 (0x00007fb5e1198000)
	libc10.so => not found
	libtorch.so => not found
	libtorch_cpu.so => not found
	libtorch_python.so => not found
	libstdc++.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libstdc++.so.6 (0x00007fb5de61d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb5dfd22000)
	libgcc_s.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/libgcc_s.so.1 (0x00007fb5e1160000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb5de400000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb5e12cb000)
	libvpx.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libvpx.so.8 (0x00007fb5de209000)
	libiconv.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libiconv.so.2 (0x00007fb5df919000)
	liblzma.so.5 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./liblzma.so.5 (0x00007fb5e1130000)
	libdav1d.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libdav1d.so.6 (0x00007fb5de011000)
	libaom.so.3 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libaom.so.3 (0x00007fb5dd800000)
	libmp3lame.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libmp3lame.so.0 (0x00007fb5dfcaa000)
	libopus.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libopus.so.0 (0x00007fb5ddfb0000)
	libSvtAv1Enc.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libSvtAv1Enc.so.1 (0x00007fb5dd000000)
	libx264.so.164 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libx264.so.164 (0x00007fb5dcc00000)
	libx265.so.199 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libx265.so.199 (0x00007fb5db800000)
	libopenh264.so.7 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libopenh264.so.7 (0x00007fb5dcedf000)
	libz.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libz.so.1 (0x00007fb5e1111000)
	libva.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva.so.2 (0x00007fb5ddf7f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb5e110c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb5e1107000)
	libxml2.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libxml2.so.2 (0x00007fb5dca97000)
	libbz2.so.1.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libbz2.so.1.0 (0x00007fb5dfc96000)
	libgnutls.so.30 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libgnutls.so.30 (0x00007fb5db400000)
	libva-drm.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva-drm.so.2 (0x00007fb5e1100000)
	libva-x11.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libva-x11.so.2 (0x00007fb5e10f9000)
	libX11.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./libX11.so.6 (0x00007fb5db6bb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fb5df914000)
	libicui18n.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicui18n.so.73 (0x00007fb5db000000)
	libicuuc.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicuuc.so.73 (0x00007fb5dac00000)
	libicudata.so.73 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libicudata.so.73 (0x00007fb5d8c00000)
	libp11-kit.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libp11-kit.so.0 (0x00007fb5daed2000)
	libidn2.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libidn2.so.0 (0x00007fb5ddf2c000)
	libtasn1.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libtasn1.so.6 (0x00007fb5df8ff000)
	libnettle.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libnettle.so.8 (0x00007fb5dd7aa000)
	libhogweed.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libhogweed.so.6 (0x00007fb5db663000)
	libgmp.so.10 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libgmp.so.10 (0x00007fb5db358000)
	libdrm.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libdrm.so.2 (0x00007fb5de606000)
	libXext.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libXext.so.6 (0x00007fb5ddf17000)
	libXfixes.so.3 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libXfixes.so.3 (0x00007fb5ddf0e000)
	libX11-xcb.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libX11-xcb.so.1 (0x00007fb5ddf09000)
	libxcb.so.1 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libxcb.so.1 (0x00007fb5dd77e000)
	libxcb-dri3.so.0 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/././libxcb-dri3.so.0 (0x00007fb5ddf03000)
	libffi.so.8 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libffi.so.8 (0x00007fb5dcece000)
	libunistring.so.2 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libunistring.so.2 (0x00007fb5d8a7b000)
	libXau.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libXau.so.6 (0x00007fb5dcec9000)
	libXdmcp.so.6 => /home/nicolashug/.miniconda3/envs/ffmpeg6/lib/./././libXdmcp.so.6 (0x00007fb5dca8f000)

```

```
(ffmpeg6) ➜  vision git:(fix-with-ffmpeg6) ✗ python lol.py 
pyav
video_reader
/home/nicolashug/vision/torchvision/io/_video_opt.py:443: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  warnings.warn(
torch.Size([83, 240, 320, 3])
torch.Size([3, 240, 320])

```

</details>
